modLoader="javafml" 
loaderVersion="${loader_range}"
license="MIT"

issueTrackerURL="https://github.com/Mrthomas20121-Mods/tinkersworld/issues"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] 
modId="tinkers_world" 
version="${file.jarVersion}" 
displayName="Tinkers World" 
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/Mrthomas20121-Mods/tinkersworld" #optional
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional
credits="TinkersEnergistics for the 1.16.5 tinkers dependency example" #optional

authors="Mrthomas20121" #optional
description='''
Addons for tinkers construct.
'''
[[dependencies.tinkers_world]]
    # the modid of the dependency
    modId="forge" 
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true 
    # The version range of the dependency
    versionRange="${forge_range}" 
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
[[dependencies.tinkers_world]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkers_world]]
    modId="mantle"
    mandatory=true
    versionRange="${mantle_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkers_world]]
    modId="tconstruct"
    mandatory=true
    versionRange="${tconstruct_range}"
    ordering="NONE"
    side="BOTH"